### ISSUE TITLE
cellrender won't give any results

### ISSUE THREAD

**Issue by IAMHUIHUI** [broadinstitute/CellBender#101]
I have been trying to get CellBender running for the past two days. however, it always stopped working after it prints 'Optimal posterior regularization factor=' for me. No results after the run either, only the log file. Any idea why?

Thanks,
Huihui

**Comment by sjfleming** [comment]
Hi @IAMHUIHUI , it sounds like maybe something else is going on if the sample is running for that long.  I do not usually run this on CPU.  Without a GPU it will take a long time, but 12 hours seems like a lot.  Can I see your log file?  Maybe I can make a few suggestions.

**Comment by IAMHUIHUI** [comment]
Thanks, Stephen! Attached please find the log file. I was not able to download your test files. So I used my cellranger mapping, but with epochs 1.

 

Best, 

Huihui

 

From: Stephen Fleming ***@***.***
Reply-To: broadinstitute/CellBender ***@***.***>
Date: Wednesday, May 12, 2021 at 4:23 PM
To: broadinstitute/CellBender ***@***.***>
Cc: IAMHUIHUI ***@***.***>, Mention ***@***.***>
Subject: Re: [broadinstitute/CellBender] cellrender won't give any results (#101)

 

Hi @IAMHUIHUI , it sounds like maybe something else is going on if the sample is running for that long. I do not usually run this on CPU. Without a GPU it will take a long time, but 12 hours seems like a lot. Can I see your log file? Maybe I can make a few suggestions.

**Comment by sjfleming** [comment]
Hi Huihui, I am not able to see the log file here on GitHub.  I am not finding an attachment.  Maybe can you email it to me at sfleming@broadinstitute.org ?  Thanks

**Comment by iddryg** [comment]
@FanBioinformatics @sjfleming What was the verdict here?
