### ISSUE TITLE
Runtime error

### ISSUE THREAD

**Issue by komalbollepogu** [broadinstitute/CellBender#105]
Hello, Thank you for the wonderful tool. I was able to run cellbender successfully, but when I tried running again, I have been getting an error. Can you please let me know where I am doing it wrong? Thank you!
![error](https://user-images.githubusercontent.com/43685715/122976770-5ca88f00-d35a-11eb-9acf-8667ffed364f.JPG)

**Comment by franciscogrisanti** [comment]
Had the same error @komalbollepogu. It was fixed downgrading torch to 1.8, the current conda installation points to 1.9

Best, 

Francisco

**Comment by komalbollepogu** [comment]
> Had the same error @komalbollepogu. It was fixed downgrading torch to 1.8, the current conda installation points to 1.9
> 
> Best,
> 
> Francisco

Thank you! I will try that and see.

**Comment by sjfleming** [comment]
@franciscogrisanti Thanks for the fix, and @komalbollepogu thanks for reporting this.  I will try to look into this and make sure we don't need to downgrade to any particular pytorch version in the future.

**Comment by sjfleming** [comment]
Closed by #238
