### ISSUE TITLE
Report the UMIs in the filtered barcodes before/after ambient RNA correction?

### ISSUE THREAD

**Issue by apredeus** [broadinstitute/CellBender#112]
I was wondering if it would be possible to make a small logging improvement in the new version. 

It's always interesting to see the amount of RNA (number of UMIs or percentages) removed from the filtered barcodes specifically. I've done this analysis few times in `Seurat` or `Scanpy`. I think it would be really nice to have it printed to the logs, alongside with the sum total of all UMIs in all droplets. 

Thank you very much in advance!

**Comment by sjfleming** [comment]
Yes, that sounds like a nice idea.  I do plan to have a more extensive output report saved in HTML format in the near future with the next release.  But I guess it would also be nice to have those numbers in the log.  Can't hurt!

**Comment by sjfleming** [comment]
Well I didn't end up putting it in the log, but these kinds of numbers are now visible in the HTML report as well as the metrics.csv output file, which summarizes a lot of general information about what happened.

Closed by #238
