### ISSUE TITLE
Does cellbender work with citeseq data?

### ISSUE THREAD

**Issue by smk5g5** [broadinstitute/CellBender#114]
Does cellbender work with 10x citeseq data?

**Comment by sjfleming** [comment]
One more thing to point out is that it is probably beneficial to try several values of "--fpr" when working with antibody capture data.  Since there is so much additional background noise for most antibody capture, sometimes it is helpful to increase the FPR in order to increase noise removal.

**Comment by sjfleming** [comment]
Add mention of this in the docs

**Comment by ktpolanski** [comment]
I gave cellbender a try on CITE data based on this discussion, and the results have been encouraging. I had to use a stratospheric 0.9 for the FPR, but in the end I was able to coax out profiles with a good portion of the soup removed.

Given the fact CITE is inherently soupier than GEX via experimental factors, would it make sense to model their backgrounds separately? Maybe have a more trigger-happy model for the CITE? Accepting separate FPRs for the two modalities seems like a reasonable heuristic, but maybe there's something smarter that could be done at an algorithm level?

**Comment by sjfleming** [comment]
@ktpolanski you make a very interesting point.  With the public 10x Genomics pbmc5k dataset above, things kind of worked out that the gene expression and antibody features both cleaned up very nicely at about FPR 0.1, which is pretty reasonable.  If you are having to go to FPR 0.9, that does represent a massive deviation from what we'd expect.

Two-part answer:

(1) We will (within a few weeks) be releasing cellbender v0.3.0, which constructs the denoised count matrix in a slightly different way from v0.2.  In particular, it has per-feature noise removal targets that it tries to hit, based on the dataset.  These per-feature targets might be exactly what's needed to fix the issue you're seeing.

(2) If that does not end up fixing the issue you've described, then it is reasonable to consider different alternatives.  We'd definitely like it to work well on both modalities without having to run twice using different FPR settings.  As you say, it does make sense to model their backgrounds separately.  But the current model _does_ basically model all features separately.  If one feature has way higher background than another (or one feature type), then the model should be able to learn that without a problem.  If (1) doesn't fix the issue, then we might need to consider some tweaks to the model in the medium-term, starting out with figuring out why the antibody features maybe are not obeying the assumptions in our model, or if there is some other noise mechanism at play for antibody capture features (though I don't see what it would be...)

**Comment by ktpolanski** [comment]
Thanks for the response, all of the above sounds very promising. Looking forward to trying out v0.3.0.

**Comment by mdmanurung** [comment]
Is there an estimate of when the v.0.3.0 will be released? Thanks in advance.

**Comment by sjfleming** [comment]
@mdmanurung 
My time estimates are clearly way too optimistic.  I have done a whole lot of refactoring, but I think I'm pretty much done.  The draft I'm working on is in the branch called `sf_dev_0.3.0_postreg`.  I want to add one more new output file, and potentially modify the heuristics for computing priors, but that's about it.  I'd estimate about a month before it all actually undergoes code review and gets merged and released.

**Comment by sjfleming** [comment]
#189

**Comment by sjfleming** [comment]
Closed by #238 

https://www.nature.com/articles/s41592-023-01943-7/figures/6
