### ISSUE TITLE
Output structure depends on input

### ISSUE THREAD

**Issue by barkasn** [broadinstitute/CellBender#119]
**Problem**

- The H5 output file structure depends on the input files used (h5 or mtx) without any indication in documentation or during execution

**Details**

- When running cellbender with the mtx files as input the output h5 file does not have the expected structure (as defined in the tutorial). Specifically the data are under 'matrix/' and they in addition seem to be missing some of the auxiliary data required. What is missing exactly is not clear, but the resulting file failed to load in scanpy.

**Suggested** solution

- Add a warning when running with mtx input

**Comment by sjfleming** [comment]
Thanks for documenting this, Nick, I will make sure it's fixed with the next release

**Comment by sjfleming** [comment]
Closed by #238
