### ISSUE TITLE
Terra workflow remove-background fails to run

### ISSUE THREAD

**Issue by mhulke** [broadinstitute/CellBender#120]
I've used Cellbender via the Terra workflow (v11) without issue in the past. Recently, I have the problem where a submitted job will run indefinitely without progress. I usually use the default docker image, but also recently tried the docker image "sjfleming/cellbender:latest" thinking maybe the docker image was causing problems. All inputs are default except fpr is set to 0.01. I am still able to submit other workflows in Terra, and they run to completion without any problem. Any help with this issue would be greatly appreciated.

**Comment by mhulke** [comment]
The workflow finally crashed after sitting in submit for a long time and then attempting to run the workflow for 10hrs. It produced the following error:
2022/01/25 07:26:24 Starting container setup.
2022/01/25 07:26:25 Done container setup.
2022/01/25 07:26:27 Starting localization.
2022/01/25 07:26:35 Localization script execution started...
2022/01/25 07:26:35 Localizing input gs://fc-995fb924-5352-4ca8-8b65-fb80ea462c5b/multimodal/arc_count/1960/raw_feature_bc_matrix.h5 -> /cromwell_root/fc-995fb924-5352-4ca8-8b65-fb80ea462c5b/multimodal/arc_count/1960/raw_feature_bc_matrix.h5
2022/01/25 07:26:40 Localizing input gs://fc-995fb924-5352-4ca8-8b65-fb80ea462c5b/3f5fa56b-5ae8-4751-81b1-fbb39f106903/cellbender_remove_background/e9452a10-abdd-4c83-b84f-bc835f880162/call-run_cellbender_remove_background_gpu/script -> /cromwell_root/script
2022/01/25 07:26:41 Localization script execution complete.
2022/01/25 07:26:46 Done localization.
2022/01/25 07:26:46 Running user action: docker run -v /mnt/local-disk:/cromwell_root --entrypoint=/bin/bash sjfleming/cellbender@sha256:84f07f0eb2367873b9cb078c3e2ea38de909fddf4147fad969ec08ed382c3621 /cromwell_root/script
usage: cellbender [-h] cellbender {remove_background} ...
cellbender: error: argument tool: invalid choice: 'remove-background' (choose from 'remove_background')
/cromwell_root/script: line 40: gsutil: command not found
ln: failed to access '/cromwell_root/1960_out*.h5': No such file or directory
2022/01/25 07:26:51 Starting delocalization.
2022/01/25 07:26:51 Delocalization script execution started...
2022/01/25 07:26:51 Delocalizing output /cromwell_root/memory_retry_rc -> gs://fc-995fb924-5352-4ca8-8b65-fb80ea462c5b/3f5fa56b-5ae8-4751-81b1-fbb39f106903/cellbender_remove_background/e9452a10-abdd-4c83-b84f-bc835f880162/call-run_cellbender_remove_background_gpu/memory_retry_rc
2022/01/25 07:26:54 Delocalizing output /cromwell_root/rc -> gs://fc-995fb924-5352-4ca8-8b65-fb80ea462c5b/3f5fa56b-5ae8-4751-81b1-fbb39f106903/cellbender_remove_background/e9452a10-abdd-4c83-b84f-bc835f880162/call-run_cellbender_remove_background_gpu/rc
2022/01/25 07:26:55 Delocalizing output /cromwell_root/stdout -> gs://fc-995fb924-5352-4ca8-8b65-fb80ea462c5b/3f5fa56b-5ae8-4751-81b1-fbb39f106903/cellbender_remove_background/e9452a10-abdd-4c83-b84f-bc835f880162/call-run_cellbender_remove_background_gpu/stdout
2022/01/25 07:26:56 Delocalizing output /cromwell_root/stderr -> gs://fc-995fb924-5352-4ca8-8b65-fb80ea462c5b/3f5fa56b-5ae8-4751-81b1-fbb39f106903/cellbender_remove_background/e9452a10-abdd-4c83-b84f-bc835f880162/call-run_cellbender_remove_background_gpu/stderr
2022/01/25 07:26:58 Delocalizing output /cromwell_root/glob-39df696d7875acbb78a1d9e43ece27c9 -> gs://fc-995fb924-5352-4ca8-8b65-fb80ea462c5b/3f5fa56b-5ae8-4751-81b1-fbb39f106903/cellbender_remove_background/e9452a10-abdd-4c83-b84f-bc835f880162/call-run_cellbender_remove_background_gpu/glob-39df696d7875acbb78a1d9e43ece27c9/
2022/01/25 07:26:59 Delocalizing output /cromwell_root/1960_out_cell_barcodes.csv -> gs://fc-995fb924-5352-4ca8-8b65-fb80ea462c5b/3f5fa56b-5ae8-4751-81b1-fbb39f106903/cellbender_remove_background/e9452a10-abdd-4c83-b84f-bc835f880162/call-run_cellbender_remove_background_gpu/1960_out_cell_barcodes.csv
Required file output '/cromwell_root/1960_out_cell_barcodes.csv' does not exist.


It seems like there might be an error in the WDL based on this line from the error message: 
cellbender: error: argument tool: invalid choice: 'remove-background' (choose from 'remove_background')
where the WDL calls 
command {
    cellbender remove-background \ . . . 

Would simply changing the WDL fix this error, or am I looking in the wrong spot?

**Comment by sjfleming** [comment]
(We discovered this may have been some kind of intermittent issue that disappeared.  It may have been something transient on google's side of things...)
