### ISSUE TITLE
Cellbender overestimate cells

### ISSUE THREAD

**Issue by maxozo** [broadinstitute/CellBender#122]
Hi, I am wondering if you could assist: 
We have been using cellbender with no issues, but recently we have a sample where cellbender dramatically overestimated the cells. While cellranger filtering produces 27k cells which we would expect, cellbender yields 65k, removing a very small proportion of the barcodes. I have tried running by feeding in the --expected cells (cellranger counts as well as cellranger counts -1000), and without this parameter to base it on the curve.
Is there anything else I could try to get the more representative number of cells ~ 27k as per cellranger filtering?
See attached comparison of curves:
<img width="1007" alt="Screenshot 2022-02-06 at 12 15 54" src="https://user-images.githubusercontent.com/22347136/152680313-b39d3afe-3fbd-415a-b455-44b62acf0b47.png">

**Comment by maxozo** [comment]
Just adding to this, cellranger is capable in estimating around 27k cells as per image attached, and were expecting cellranger to have about the same. 
The cellbender command used was - 
`cellbender remove-background --input txd_input --cuda --output cellbender --expected-cells 26214 --total-droplets-included 251749 --model full --z-dim 100 --z-layers 500 --low-count-threshold 10 --epochs 250 --learning-rate 1E-7 --fpr 0.01 0.05 0.1` - as mentioned, I have runned with and without `--expected-cells`
![Screenshot 2022-02-07 at 14 07 41](https://user-images.githubusercontent.com/22347136/152803403-eb408d4b-7cce-4008-995b-8c1530754358.png)

**Comment by sjfleming** [comment]
Hi @maxozo , thanks for your question and sorry for the delay.

Yes, hopefully there is a simple fix.  Cellbender uses certain assumptions to make guesses about where the "empty droplet plateau" is, and I can see that this dataset might be throwing it off by violating some of those assumptions.

If you look at the log file produced by cellbender, I am guessing you will see that the "empty droplets" are estimated to have < 100 counts per droplet.  I think it is probably picking up that second plateau.  You can force it to avoid this behavior by including the argument `--low-count-threshold`, and setting it to some value above that second plateau.  For example, I think `100` would work well.  This will effectively tell cellbender to totally ignore any data where a barcode has less than 100 counts.  That actually does seem appropriate for this particular dataset, where I am seeing that the "real" ambient plateau has something like 2000 counts per droplet.

Also, I think the `expected-cells` you are using is okay, though you could maybe go with 20000 or something, but it shouldn't matter.  On the other hand, `total-droplets-included` is probably too large.  It is probably taking a very long time to run.  You can speed things up a great deal by reducing this value.  If you know that certain barcodes are "surely empty", then you do not need to include them in `total-droplets-included`.  The algorithm will still look at the "surely empty" droplets, but it doesn't look at them as often, and it doesn't have to try to determine if they have a cell: it knows they are "surely empty".  So in your dataset, it's hard for me to see, but maybe by 30000 or 35000, you know the droplets are all empty.  So maybe you could say 35000 if you want to be more conservative.  One last thing: that learning rate might be a bit too small.  If you have problems with the default of 1e-4, then I would suggest 5e-5, but not much smaller than that.

In total, the suggested command would look like
```
cellbender remove-background --input txd_input --cuda --output cellbender --expected-cells 20000 --total-droplets-included 35000 --low-count-threshold 100 --epochs 250 --learning-rate 5e-5 --fpr 0.01 0.05 0.1
```

**Comment by sjfleming** [comment]
Also, @maxozo , this is one single 10x run from one channel, right?  You are not combining data from multiple runs into one dataset?

**Comment by maxozo** [comment]
Thank you for this, very useful! We are not combining data, this is from one Channel.
