### ISSUE TITLE
filtered.h5 matrix is strange

### ISSUE THREAD

**Issue by baigal628** [broadinstitute/CellBender#131]
Hi,

Thanks for developing this tool!

I ran CellBender using the below command and got the filtered.h5 matrix. While I read the output into Seurat, I found roughly half of the genes have 0 expressions and the majority of the genes that are expressed have sd == 0. I am wondering if this filtered.h5 matrix is what CellBender removed but not what is left after removal. Thanks for any help!

<img width="463" alt="image" src="https://user-images.githubusercontent.com/56844380/169112978-e452ee51-f309-4d68-ab38-8225e36d37f3.png">

```{bash}
cellbender remove-background --input ./GEXdata/Pool105_1/outs/raw_feature_bc_matrix/ \
--output ./GEXdata/Pool105_1/outs/Pool105_1.h5 \
--expected-cells 3000 \
--total-droplets-included 20000 \
--epochs 150
```

```{r}
mtx_out <- Read10X_h5(
    filename = "./data/GEXdata/Pool105_1/outs/Pool105_1_filtered.h5", 
    use.names = TRUE)

mtx_out  %>% dim()
#32285 9901
sum(rowSums(mtx_out)>0)
#18266
```

```{r}
matrix<- as.matrix(mtx_out)

matrix <- matrix[rowSums(matrix)>0, ]

rowsds <- apply(log2(matrix+1), 1, sd)
plot(density(rowsds)

```
<img width="504" alt="image" src="https://user-images.githubusercontent.com/56844380/169110757-667f4298-44bd-47cc-a1a9-752f2abccbf8.png">

```{r}
top10 <- head(VariableFeatures(obj), 10)
# plot variable features with and without labels
plot1 <- VariableFeaturePlot(obj)
plot2 <- LabelPoints(plot = plot1, points = top10, repel = TRUE)
plot2

```
<img width="496" alt="image" src="https://user-images.githubusercontent.com/56844380/169112218-58c1b952-c2b6-4c5e-9dbf-bb0a9027d644.png">

**Comment by sjfleming** [comment]
Likely Closed by #238
