### ISSUE TITLE
create new 0.2.1 release ?

### ISSUE THREAD

**Issue by arielzn** [broadinstitute/CellBender#133]
hello,

I'm looking for packaging this and creating a module for using in an HPC cluster environment.
For us, is cleaner to base the install on a released source tarball, rather than pulling a given status of the git repo. 

In order to have a clear module naming for the current version, instead of using the commit tag, could you produce a new release to include all the commits present on master since 0.2.0 (released on Oct 2020) ?

I guess you  could consider current master branch `0.2.1` ?

thanks.

**Comment by arielzn** [comment]
i guess is probably worth to merge  https://github.com/broadinstitute/CellBender/pull/118  before releasing.

I needed that fix to get a proper packaged build.

**Comment by sjfleming** [comment]
Hi @arielzn , sorry for the delayed response!

We are working on some big changes coming up, with some added features and some refactoring... but that will be version 0.3.0.  Keep an eye out for that in the coming month or so.

For now, yes, I can merge #118 and cut a new release.  Done!
