### ISSUE TITLE
length of the barcode

### ISSUE THREAD

**Issue by xul0621** [broadinstitute/CellBender#150]
Hi, 

I am running CellBender on my snRNA-seq data. According to the sequencing company, each droplet have a barcode with 27 letters. After running CellBender I found only the first 20 letters were stayed which leads to the uniqueness of the barcodes. I checked the parameters, there seems no parameter was used to adjusted this. 

I have no idea on how to solve this problem. Could you give me any suggestions?

Thank you in advance!

**Comment by sjfleming** [comment]
Hi @xul0621 , sorry for the delayed response.

What is the file format for your dataset?  CellBender can load several datatypes, and once I know which file format you used, then maybe I can look and see what happened.  Off the top of my head, it doesn't seem like CellBender should be truncating the barcodes.  It's supposed to leave them as they are, and not have any hard-coded requirements about length.

**Comment by xul0621** [comment]
Thanks for your reply. 
I found that if I use the folder path, which contain the barcodes.tsv, genes.tsv and matrix.mtx as the input. The output of the CellBender (the h5 file) have only 20 lettersfor the barcode. In this case, I found that the format of the CellRanger is v2 in the log file. 
Therefore, I tried to use the h5 format as the input. This time, the output barcode have 27 letters. I test the version of the h5 input, no matter v2 or v3 will not affect the CellBender results.
I guess, the problem will be the reading process in the algrothem from the folder path. 
Thanks again for you attention.


> Hi @xul0621 , sorry for the delayed response.
> 
> What is the file format for your dataset? CellBender can load several datatypes, and once I know which file format you used, then maybe I can look and see what happened. Off the top of my head, it doesn't seem like CellBender should be truncating the barcodes. It's supposed to leave them as they are, and not have any hard-coded requirements about length.

**Comment by sjfleming** [comment]
Hi @xul0621, thank you very much for letting me know that.  That is very helpful information.  I will be sure to take another look at the data loader for the folder path, and I'll modify it so that it doesn't have any hard-coded expectations about barcode length.

And thanks for posting the fix about using the h5 file!

**Comment by sjfleming** [comment]
Note to self: yes, here it is, the dtype is the problem... I may have copied this from 10x.  `dtype=str` will probably fix this.
https://github.com/broadinstitute/CellBender/blob/cb2d209d5aedffe71e28947bc5b7859600aef64d/cellbender/remove_background/data/dataset.py#L891-L892

**Comment by sjfleming** [comment]
Closed by #238
