### ISSUE TITLE
CUDA device busy or not available when other processes are running on the same node

### ISSUE THREAD

**Issue by edg1983** [broadinstitute/CellBender#162]
Hello,

I'm still struggling with this issue that we considered resolved a while ago (#127 ).

Sorry but this problem is here again.
After a long investigation, what I can say is that cellbender fails randomly when it is running on a node with GPUs where there are also other jobs.
When I make a request so that a whole node is assigned to my cellbender process everything is fine. In our system configuration, NVIDIA GPUs running mode is set to default, which allows sharing of GPUs.If I understand correctly what this means, multiple processes can share the same GPU.

Do you think cellbender may require exclusive access to a GPU and thus resulting in the error above when it happens to be another process on the same GPU?

As I said, I do not see this problem with other GPU-enabled tools, so it may be something specific in the pytorch implementation of cellbender.

Can you help with this? It is really hard to run cellbender for batches of datasets in the current situation since some of them will always fail randomly.

**Comment by sjfleming** [comment]
Hi @edg1983 ,

Sorry to hear this... I'm afraid I am a little bit out of my depth here.  I can tell you that cellbender does hog quite a bit of GPU memory, which it expects to be available to it the entire time (most deep learning tools that use GPUs do this, as far as I know).

I would assume that you might be right: it's probably the case that cellbender requires exclusive use of a GPU.

But let me tag in some help from others who may know more than I do @mbabadi @fritzo @eb8680 

Anybody know if the kind of GPU-sharing mentioned above could be expected to work in this case?

**Comment by fritzo** [comment]
You should be able to set different processes to use different [cuda streams](https://pytorch.org/docs/stable/generated/torch.cuda.Stream.html)

**Comment by sjfleming** [comment]
@fritzo thanks for your help!  Is that something I would do within cellbender, or is that something that @edg1983 would do when running cellbender on his HPC cluster?

**Comment by fritzo** [comment]
@sjfleming well I'm no expert on CUDA streams, and they might not be the right solution to resolve inter-process blocking but...

It looks like the PyTorch interface to cuda streams is a python interface (I see no environment variables).  So if your users are running CellBender as a script you'd probably need to add say an optional command line arg and a context manager like this:
```python
parser.add_argument("--cuda-stream", action="store_true")
...
args = parser.parse_args()
if args.cuda_stream:
    stream = torch.cuda.Stream():
    with torch.cuda.stream(stream):
        main(args)
else:
    main(args)
```
Again I'm no expert and this may not solve your problem.

@edg1983 could you paste an error message or log entry of one of your failed jobs?  Do you think this is an OOM error?

**Comment by sjfleming** [comment]
Thanks very much @fritzo !

**Comment by edg1983** [comment]
Hi,

Apologize for the slow reply here. Essentially, when I submit a cellbender process to SLURM requesting a single GPU (`gres=gpu:1`) I often get the following error, which I think is due to sharing of GPU usage, but not out of mem.

```
cellbender:remove-background: Command:
  cellbender remove-background --input filtered_feature_bc_matrix.h5 --output BCP008.h5 --fpr 0.01 --cuda
  cellbender:remove-background: 2022-04-14 13:13:39
  cellbender:remove-background: Running remove-background
  cellbender:remove-background: Loading data from file filtered_feature_bc_matrix.h5
  cellbender:remove-background: CellRanger v3 format
  cellbender:remove-background: Trimming dataset for inference.
  cellbender:remove-background: Including 19694 genes that have nonzero counts.
  cellbender:remove-background: Prior on counts in empty droplets is 3293
  cellbender:remove-background: Prior on counts for cells is 21333
  cellbender:remove-background: Excluding barcodes with counts below 1646
  cellbender:remove-background: Using 646 probable cell barcodes, plus an additional 1977 barcodes, and 0 empty droplets.
  cellbender:remove-background: Largest surely-empty droplet has 1646 UMI counts.
  Traceback (most recent call last):
    File "/home/user/miniconda/bin/cellbender", line 11, in <module>
      load_entry_point('cellbender', 'console_scripts', 'cellbender')()
    File "/cellbender/cellbender/base_cli.py", line 101, in main
      cli_dict[args.tool].run(args)
    File "/cellbender/cellbender/remove_background/cli.py", line 103, in run
      main(args)
    File "/cellbender/cellbender/remove_background/cli.py", line 196, in main
      run_remove_background(args)
    File "/cellbender/cellbender/remove_background/cli.py", line 160, in run_remove_background
      inferred_model = run_inference(dataset_obj, args)
    File "/cellbender/cellbender/remove_background/train.py", line 235, in run_inference
      use_cuda=args.use_cuda)
    File "/cellbender/cellbender/remove_background/model.py", line 84, in __init__
      self.cuda()
    File "/home/user/miniconda/lib/python3.7/site-packages/torch/nn/modules/module.py", line 307, in cuda
      return self._apply(lambda t: t.cuda(device))
    File "/home/user/miniconda/lib/python3.7/site-packages/torch/nn/modules/module.py", line 203, in _apply
      module._apply(fn)
    File "/home/user/miniconda/lib/python3.7/site-packages/torch/nn/modules/module.py", line 203, in _apply
      module._apply(fn)
    File "/home/user/miniconda/lib/python3.7/site-packages/torch/nn/modules/module.py", line 203, in _apply
      module._apply(fn)
    File "/home/user/miniconda/lib/python3.7/site-packages/torch/nn/modules/module.py", line 225, in _apply
      param_applied = fn(param)
    File "/home/user/miniconda/lib/python3.7/site-packages/torch/nn/modules/module.py", line 307, in <lambda>
      return self._apply(lambda t: t.cuda(device))
  RuntimeError: CUDA error: all CUDA-capable devices are busy or unavailable
```

This never happens if I change the SLURM submission settings so that my job takes a whole GPU node (thus it is "isolated" in the node without any other process).

**Comment by edg1983** [comment]
Hello!

I realize it's been a while since my last update, but I was distracted by other commitments. I did several tests on this issue and also discussed a lot with our IT team how GPU nodes are configured and managed by the scheduler.

Basically, our GPUs are configured with E.process running mode, and then the scheduler assigns each process to one or more GPUs. The "process exclusive" access should, in theory, prevent conflicts from happening. My tests confirmed that a process is not sent to an already-used GPU when submitting a simple task.

In the end, I found out that the issue is likely related to singularity or, more specifically, how it is managed inside a Nextflow workflow. When I want to run a container with GPU support, I usually rely on the singularity --nv option like `singularity exec --nv <container> <command>`

When trying this manually, I can see that the CUDA_VISIBLE_DEVICES env variable inside the container is correctly set to resemble the one set by the scheduler. However, when using NextFlow, this variable is not set in the container process, and thus, any tool using cuda inside does not know which GPU device was reserved for it.
Adding `containerOptions='--nv --env CUDA_VISIBLE_DEVICES=$CUDA_VISIBLE_DEVICES'` force singularity to import the env variable, and now the problem seems solved.

**Comment by sjfleming** [comment]
Wow @edg1983 , you did some amazing detective work there.  Thank you so much for posting this so everybody can learn from it!  This seems really useful to know.  Might even be something that NextFlow would want to address on their side too, so people don't have to do so much work to get things configured properly
