### ISSUE TITLE
Use CellBender latent representation for the UMAP

### ISSUE THREAD

**Issue by jessijessi** [broadinstitute/CellBender#183]
Hi everybody, I used CellBender to remove background from my single cell RNAseq samples but when I tried to use the CellBender latent representation for the UMAP, in Scanpy, I obtained a UMAP in which the batches are splitted, as shown in the picture below:

![immagine](https://user-images.githubusercontent.com/72512371/226363575-25db4f9f-3fa0-4ab2-9afc-4f79fd8ffdc2.png)

Why the batches are splitted? How can I obtain a UMAP in which the samples are not separeted? Should I use the CellBender latent gene encoding to compute the UMAP or not?

Thank you,
Best regards

**Comment by sjfleming** [comment]
Hi @jessijessi , I would recommend not using the CellBender latent representation to make a UMAP when you have multiple datasets that you are integrating together in a project.

While the CellBender latent representation is interesting to look to for one dataset alone, the fact that CellBender runs separately and independently on each dataset means that the latent representation of gene expression it learns is also separate and independent for each sample.  So we would not expect good alignment of the latent spaces from two CellBender runs.

I would personally recommend a tool specifically built for this type of dataset integration downstream.  One method that uses a very similar, principled approach for dataset integration is `scVI` (https://www.nature.com/articles/s41592-018-0229-2).

When I want to run CellBender on several datasets and then analyze everything jointly (which is my most common use case), I do the following:

1. Run CellBender on each sample separately
2. Carefully perform cell QC on each sample separately
3. Use the CellBender-correted count matrix as an input to `scVI`, and use the jointly-learned, batch-effect-corrected latent space learned by `scVI` (on the denoised counts) to produce an integrated UMAP

**Comment by sjfleming** [comment]
That is correct, yes!

**Comment by jessijessi** [comment]
Thank you @sjfleming
