### ISSUE TITLE
question about parameters

### ISSUE THREAD

**Issue by wbvguo** [broadinstitute/CellBender#192]
Hi, 

Thanks for maintaining this tool. Choosing a threshold is always subjective. May I ask if CellBender provides an automatical way to specify the parameters for `--expected-cells` and `--total-droplets-included`? if not, would this be in the future plan?

Thanks,
Wenbin

**Comment by sjfleming** [comment]
Hi Wenbin,

Yes, CellBender does provide an automatic way to set those parameters, although it is not that great as of version `0.2.1`, I will admit.  It does fine on "easy" datasets, but there are a lot of datasets out there that are not so easy.

Right now, you can simply run the command without including the arguments `--expected-cells` or `--total-droplets-included` at all.  They are optional.  If you do not provide them, CellBender will make its best guess.

I am actively working to make these guesses better for version 0.3.0, and I think I have made a lot of progress.  If you want to try the very latest version and see if it works better, you can try to install from the branch called `sf_dev_0.3.0_postreg`.  Or if you prefer, you can wait for the official v0.3.0 release.  That will be out as soon as #189 gets merged.

For advice on how to set the values of `--expected-cells` or `--total-droplets-included` yourself, see the notes here:
https://cellbender.readthedocs.io/en/latest/usage/index.html#recommended-best-practices

Thanks,
Stephen

**Comment by sjfleming** [comment]
Just now released v0.3.0 which should do a much better job estimating those parameters for you.  Now you really should not need to include the input arguments `--expected-cells` or `--total-droplets-included` at all.

Closed by #238
