### ISSUE TITLE
Error while trying to load cellbender filtered output to scanpy

### ISSUE THREAD

**Issue by unikill066** [broadinstitute/CellBender#217]
I processed a sample file using CellBender to eliminate ambient RNA, using the below-mentioned arguments;
```
cellbender 
    remove-background 
    --input *.h5
    --output output.h5 
    --expected-cells 10000 
    --total-droplets-included 20000 
    --fpr 0.01 
    --epochs 150
```

Additionally, I encountered an error when attempting to load the filtered output file into the scanpy library using the `read_10x_h5` function;
### Code
```
import scanpy as sc
adata = sc.read_10x_h5(r'output_filtered.h5', genome='background_removed')
```
### Error
```
ValueError: Could not find data corresponding to genome 'background_removed' 
in 'output_filtered.h5'. Available genomes are: ['GRCh38'].
```

**Comment by unikill066** [comment]
Additionally, if we use `GRCh38` instead of `background_removed` while loading the data, the functionality works, however `background_removed.latent_gene_encoding.read()` throws an error.

### Error
```
NoSuchNodeError: group ``/`` does not have a child named ``background_removed``
```

**Comment by sjfleming** [comment]
Hi @unikill066 , are you using cellbender 0.2 ?  (You're not working from a development branch in this GitHub repository?)

It sounds like
```python
import scanpy as sc
adata = sc.read_10x_h5('output_filtered.h5', genome='GRCh38')
```
did work for you, is that right?

How did you try to use `background_removed.latent_gene_encoding.read()`?  Something like [this](https://cellbender.readthedocs.io/en/latest/getting_started/remove_background/index.html#use-latent-gene-expression-in-downstream-analyses)?
```python
import tables

with tables.open_file('output_filtered.h5', 'r') as f:
    print(f)
    latent_gene_expression = f.root.background_removed.latent_gene_encoding.read()  # read latents
```
and then you can use `latent_gene_expression` downstream, for example like this
```python
adata.obsm['X_cellbender_latent'] = latent_gene_expression
```

**Comment by sjfleming** [comment]
Will close this for now, feel free to re-open
