### ISSUE TITLE
Converged inference but uncertain cell probabilities

### ISSUE THREAD

**Issue by mariecrane** [broadinstitute/CellBender#219]
In the quality control checks section of your documentation, it states "A converged inference procedure should result in the vast majority of cell probabilities being very close to either zero or one." However, I have noticed several instances where the inference procedure appears to have converged, but there are several droplets with uncertain cell probabilities, between ~0.1 and 0.6. I have attached the barcode rank plot from CellRanger and the pdf output of CellBender run with the following command: `cellbender remove-background --input MGI2142_GLAE-MC_repool-MC8/outs/raw_feature_bc_matrix.h5 --output 00_CellBender/MC8/CB_filtered_feature_bc_matrix.h5 --cuda --expected-cells 2000 --total-droplets-included 15000`

Is there some way to get more definitive predictions from CellBender, with probabilities closer to 0 or 1? Thank you! 

![MC8_barcode_rank](https://github.com/broadinstitute/CellBender/assets/35476290/99f06b1a-6e13-4cb0-a0db-cdcc7e746b3c)
[CB_troubleshooting.pdf](https://github.com/broadinstitute/CellBender/files/11518725/CB_troubleshooting.pdf)

**Comment by sjfleming** [comment]
Hi @mariecrane , that looks like an interesting example.  I haven't seen one that looks exactly like that before, but I have seen samples where the cell probabilities have a lot of intermediate values.

I'd say that if you want those probabilities to converge more, the only thing to try would be to increase the number of `--epochs` for training.  The default that you see on your plot there is 150 training epochs.  I'd say you could try 300 and see what that looks like!  (I wouldn't go very much higher than that...)

**Comment by mariecrane** [comment]
Thanks for the suggestion Stephen! I tried increasing `--epochs` to 300 and here's what I got. There's still quite a few droplets with cell probabilities up to 0.2 but it's much better than the previous attempt with  probabilities up to 0.6. I feel more confident with this result now.
[CB_troubleshooting_v2.pdf](https://github.com/broadinstitute/CellBender/files/11533579/CB_troubleshooting_v2.pdf)
