### ISSUE TITLE
Difference in array size of 'features_analyzed_inds' and 'ambient_expression'

### ISSUE THREAD

**Issue by racng** [broadinstitute/CellBender#262]
I am looking through the unfiltered h5 output from cellbender v0.3.0 (performed on same 10x pbmc dataset as your notebook example) and trying to map just a few droplet/feature variables into AnnData. I have verified that the `barcodes_analyzed` has the same length as droplet properties like `cell_probability`.
However, the length of `features_analyzed_inds` is smaller than that of `ambient_expression`. Should they be the same size? 

```
import h5py
d = {}
keys = {
	'global_latents':['ambient_expression'],
	'droplet_latents': [
		'cell_probability', 
		'background_fraction', 
		'gene_expression_encoding'],
}

with h5py.File(h5, 'r') as f:
	for k in keys:
		for v in keys[k]:
			d[v] = f[k][v][()]
	d['gene_ids'] = f['matrix']['features']['id'][()]
	

len(d['ambient_expression']), len(d['features_analyzed_inds']),
# Output (33570, 13873)
len(d['cell_probability']), len(d['barcodes_analyzed']),
# Output: (9054, 9054)
```

**Comment by racng** [comment]
Oh sorry I misunderstood. I see that ambient_expression is available for all features.

**Comment by sjfleming** [comment]
Exactly right!
