### ISSUE TITLE
Make a v0.1 Docker image + update Terra workflow

### ISSUE THREAD

**Issue by mbabadi** [broadinstitute/CellBender#27]

**Comment by sjfleming** [comment]
Docker image made and uploaded to 
`us.gcr.io/broad-dsde-methods/cellbender`

**Comment by sjfleming** [comment]
New WDL written for Terra method at
`https://portal.firecloud.org/#methods/broad-dsde-methods/cellbender/`

**Comment by sjfleming** [comment]
Working...
except for Array[Int] optional inputs.

**Comment by sjfleming** [comment]
Updated the WDL again, and created a new name for the method
`https://portal.firecloud.org/#methods/cellbender/remove-background/`

Array[Int] optional inputs have been changed to String to avoid difficulties specifying array inputs.
