### ISSUE TITLE
different performance between 0.2.0 and 0.3.0

### ISSUE THREAD

**Issue by huananfshi** [broadinstitute/CellBender#270]
I have previously used older version on my sample, which works fine. I updated cellbender today and reran the sample sample. However, the learning curves are bad (with downward spikes and dip in the end). is there any change for default parameter values between two versions?

**Comment by sjfleming** [comment]
Hi @huananfshi , yes there were a lot of changes that would affect the learning curve.  Hopefully the changes improve performance on most samples, but I have run into some samples where the learning curve looks worse with default parameters in v0.3.0.  The best thing to try with v0.3.0 would be to reduce the learning rate.  Maybe something like `--learning-rate 1e-5`

Please let me know if that does not solve your problem!  Happy to dig into it further.

**Comment by huananfshi** [comment]
@sjfleming Thank you for the information. I did try to reduce learning-rate and tried a few lower rates but none did the trick. For the same sample, I also tried to not assign expected/included droplets counts and it seems to work. but the same approach did not work for some other samples.

**Comment by sjfleming** [comment]
Is it possible for you to copy and paste an image here of the UMI curve for one of those examples that didn't ever work, along with the CellBender "cell probabilities" output plot?  I might be able to use that to make a guess about what's going on.

**Comment by huananfshi** [comment]
<img width="667" alt="Screenshot 2023-09-08 at 1 42 52 PM" src="https://github.com/broadinstitute/CellBender/assets/8358906/fb4f63d4-85e8-488b-81b6-646c6da74eeb">
<img width="745" alt="Screenshot 2023-09-08 at 1 43 05 PM" src="https://github.com/broadinstitute/CellBender/assets/8358906/09ccf424-c6a7-4a71-a733-9d553f6990bf">

**Comment by huananfshi** [comment]
Here is another example that reducing learning rates did not achieve the same performance as 0.2.0
<img width="676" alt="Screenshot 2023-09-08 at 1 45 57 PM" src="https://github.com/broadinstitute/CellBender/assets/8358906/abb94b87-1a01-4b7f-a373-e8a603c048c6">
<img width="877" alt="Screenshot 2023-09-08 at 1 46 02 PM" src="https://github.com/broadinstitute/CellBender/assets/8358906/9d3a0b8b-e676-496f-a8d9-55231dda53a5">
<img width="698" alt="Screenshot 2023-09-08 at 1 46 07 PM" src="https://github.com/broadinstitute/CellBender/assets/8358906/9c07f52a-5dce-4c68-88bf-91d375b82337">

**Comment by sjfleming** [comment]
Ah yes, so I do have a guess... it would be my guess that the "empty droplets" here are between 20k-65k on the UMI curve (for the first sample) or 3k-40k (for the second sample).  CellBender seems to be thinking the empty droplets are way out past that.

For the first sample, I would try `--low-count-threshold 100` and leave out the arguments `--expected-cells` and `--total-droplets-included`.

For the second sample, I would try to leave out `--expected-cells` and `--total-droplets-included`, but if you said that did not work, I would try to specify `--expected-cells 1000` and `--total-droplets-included 10000`.

**Comment by huananfshi** [comment]
@sjfleming  thank you very much for the input. I will try it out. Could you elaborate on how to choose parameters --low-count-threshold and --total-droplets-included? I have been using number closer the the elbow as --total-droplets-included but it seems to be higher than 10000 (for the second sample)

**Comment by sjfleming** [comment]
Yes, so `--low-count-threshold` is used for cases where you want to tell cellbender to totally ignore some droplets. Usually you don't have to do this, but it can help cellbender auto-find appropriate values for expected-cells and total-droplets-included in some cases, particularly if the ambient RNA level is very very high.  Basically `--low-count-threshold` helps cellbender auto-find those values more easily.

As for choosing `--total-droplets-included`, here I think there might be something more important. You only need to include as many droplets as you think might possibly contain cells (plus a couple thousand more) as `--total-droplets-included`.  The name might be a bit confusing.  This number of droplets is the number being "analyzed" by cellbender as possible-cell-containing droplets, and a determination will be made about cell probability for each one of the `--total-droplets-included`.  But... cellbender still looks at all the droplets in the dataset as it trains, even ones beyond `--total-droplets-included`.  It still uses those as examples of empties.  But unlike the `--total-droplets-included` cellbender knows that the extra droplets past `--total-droplets-included` are "surely empty".  So this helps it gauge what empties look like.

In your case, I'd estimate the first dataset has about 10k or 20k cells, so I would say that by droplet 30k, I'm "very confident" that everything past that is empty.  So I'd set `--total-droplets-included 30000`.  But ideally, you can leave out this input argument and let cellbender auto-find it.  Similarly, for the second dataset, it looks like there are 1-2k cells.  So by droplet 10k, I'm "very confident" that all the droplets past there are empty.  And we do want to include a few thousand empties in `--total-droplets-included` as well, just to be extra safe, so I think a value of `--total-droplets-included 10000` would be quite reasonable.
