### ISSUE TITLE
cellbender v0.3.0 failed to remove ambient RNA contamination, what should I do?

### ISSUE THREAD

**Issue by YiweiNiu** [broadinstitute/CellBender#285]
Hi,

Thank you for developing such a useful tool. I am testing cellbender v0.3.0 on a 10x scRNA-seq sample, and the default settings were used.

The logs and the html look normal, with no errors or warningings. But when I compared the results of cellbender and cellranger, I found some apperant ambient RNA were not removed. I was wondering how to find the cause of this and how to solve it.

Here is a dotplot of some selected marker genes. In which we can see genes like AFP/ALB/HBA1 still pervasively expressed in all cells.

![image](https://github.com/broadinstitute/CellBender/assets/25263399/67bfc69c-2148-4401-af5d-32aab09202a1)

I also plotted genes identified as "top genes removed" in the html report of cellbender, but the differences were little.

![image](https://github.com/broadinstitute/CellBender/assets/25263399/5b542d62-a863-4c18-aa96-52767d0532b3)

I wonder how to find out the reasons behind this or if there are any parameters I could tune. Thank you in advance.

Best regards,
Yiwei

**Comment by sjfleming** [comment]
Hi @YiweiNiu , good question.  The first thing I would double-check, just to make absolutely sure, is that you're really looking at the cellbender output and not somehow looking at the raw input data by mistake.  Can you make sure that the two count matrices are different?  In python I would check like this (but I see you're using R):

```python
raw_count_matrix  # loaded raw data
cellbender_count_matrix  # loaded cellbender output file

(raw_count_matrix - cellbender_count_matrix).sum()
```
(and just make sure that these matrices are different... this output should be a positive number: the total counts removed)


Assuming that looks okay, then yes, there is a way to remove "more noise".  You can use the `--fpr` input argument.  This has a default value of 0.01, and the meaning of the value is "remove as much noise as possible, while trying to control the fraction of real signal removed to be less than this FPR value".  As you increase the `--fpr`, you will remove more noise (and some more signal too).  So it is a trade-off.


That being said, v0.3.0 includes some extra checks to ensure that the "right" amount of noise is being removed... which is to say, we try to make sure that the total counts removed for each gene is approximately equal to the amount justified by our understanding of the ambient and barcode swapping noise.

My question would be: do you have a really strong reason to expect that AFP/ALB/HBA1 are not expressed in all the cells?  This data seems like it might be immune cells.  Some genes I often see as being very noisy in this case are S100A8 and LYZ.  I see those genes in your plots, but they don't look very noisy in the raw data, so I am wondering if this dataset is very clean to begin with.  Approximately how many counts do the empty droplets have in this dataset?

**Comment by YiweiNiu** [comment]
Hi, thank you for your prompt reply and helpful suggestions.

> The first thing I would double-check, just to make absolutely sure, is that you're really looking at the cellbender output and not somehow looking at the raw input data by mistake. Can you make sure that the two count matrices are different?

Yes. I am sure they are different. I even re-ran cellbender to ensure that there's nothing wrong :)

> You can use the --fpr input argument.

I have tried to increase the `--fpr` to 0.05 and 0.1, but the results from the dotplots showed small differences. I checked the counts removed by cellbender and indeed more counts were removed when increasing the `--fpr` value.

> My question would be: do you have a really strong reason to expect that AFP/ALB/HBA1 are not expressed in all the cells?

I will consider this possibility and discuss it with other biologists.

Thank you again for your help!
