### ISSUE TITLE
Query: Using CellBender on Multiple scRNA-seq Samples

### ISSUE THREAD

**Issue by ryan2han** [broadinstitute/CellBender#321]
Hello,
I'm working with multiple scRNA-seq samples. Can I aggregate them using CellRanger aggr and then apply CellBender for background RNA correction?

**Comment by jpcartailler** [comment]
Not the author, but the amount of ambient expression is on a per-sample basis, so it would be advisable (IMO) to run each sample separately, then merge later.

**Comment by ryan2han** [comment]
Thank you for your suggestion. I did proceed in that way,
