### ISSUE TITLE
Low-dimensional representation?

### ISSUE THREAD

**Issue by ltosti** [broadinstitute/CellBender#37]
Hi there,

Is there a way to retrieve the low-dimensional representation, **z**, from the output of ```remove-background```?

Thank you!

**Comment by sjfleming** [comment]
Yes!  Try out this method in python: (`tables` refers to the [PyTables](https://www.pytables.org) package)

```python
import tables

with tables.open_file(filename, 'r') as f:
        print(f)
        z = getattr(f.root.background_removed, 'latent_gene_encoding').read()
```

At this point, the variable `z` is the (cell, z_dim) low-dimensional representation.

There's a bit more here:
https://cellbender.readthedocs.io/en/latest/getting_started/remove_background/index.html#use-latent-gene-expression-in-downstream-analyses
