### ISSUE TITLE
Fails with "not enough empty droplets" error even though --low-count-threshold 2

### ISSUE THREAD

**Issue by vitkl** [broadinstitute/CellBender#41]
CellBender fails on my data with "not enough empty droplets" error even though I set `--low-count-threshold` to 2. The error & log itself are a bit weird (look at the scale of nUMI filtered). I get this exact error (with different UMI numbers) on 2 very different datasets.

```
cellbender:remove-background: 2019-11-06 00:23:12
cellbender:remove-background: Running remove-background
cellbender:remove-background: Loading data from directory ./rawdata/filtered_feature_bc_matrix/folder
cellbender:remove-background: CellRanger v3 format
cellbender:remove-background: Trimming dataset for inference.
cellbender:remove-background: Prior on counts in empty droplets is 6001
cellbender:remove-background: Prior on counts for cells is 49252
cellbender:remove-background: Excluding barcodes with counts below 4800
Traceback (most recent call last):
  File "/path/to/software/miniconda3/envs/mypyro/bin/cellbender", line 11, in <module>
    load_entry_point('cellbender', 'console_scripts', 'cellbender')()
  File "~/CellBender/cellbender/base_cli.py", line 101, in main
    cli_dict[args.tool].run(args)
  File "~/CellBender/cellbender/remove_background/cli.py", line 92, in run
    main(args)
  File "~/CellBender/cellbender/remove_background/cli.py", line 185, in main
    run_remove_background(args)
  File "~/CellBender/cellbender/remove_background/cli.py", line 143, in run_remove_background
    args.low_count_threshold)
  File "~/CellBender/cellbender/remove_background/data/dataset.py", line 90, in __init__
    gene_blacklist=gene_blacklist)
  File "~/CellBender/cellbender/remove_background/data/dataset.py", line 252, in _trim_dataset_for_analysis
    f"There are no empty droplets with UMI counts over the lower " \
AssertionError: There are no empty droplets with UMI counts over the lower cutoff of 4800.  Some empty droplets are necessary for the analysis.Reduce the --low-count-threshold parameter.
```

**Comment by sjfleming** [comment]
Yes, so the issue here is the extremely high counts in empty droplets.  Could you post a quick picture of the UMI curve?

The algorithm believes that a good prior for real cell counts is about 49k, which sounds good for CellRanger v3 chemistry.  But the algorithm thinks that there are 6000 counts in empty droplets.  This is extremely outside the range of expectation, and that is related to why it's failing to proceed.  If I see the UMI curve, perhaps I can suggest a way forward.

**Comment by vitkl** [comment]
Thanks for a quick reply! One important caveat is that I am looking at single nucleus data (v3).
I also noticed that cellbender is much less conservative in cell calling than cellranger_v3 (Fig 7). Could that be because your model does not distinguish soup (few UMI) and debris (10s-100s UMI)? So in my case, you model considers debris as empty droplets and then picks the large 6000 prior?
 
<img width="450" alt="UMI curve" src="https://user-images.githubusercontent.com/22567383/68408966-37174380-017e-11ea-84e3-fa1907a7b5e9.png">

**Comment by sjfleming** [comment]
@vitkl This looks like a fantastic dataset.  Real cell counts right around 10k, and ambient around 200.  CellBender is really well-suited to this kind of dataset.  Because there is a lot of ambient (around 200+ counts per droplet in all likelihood), the dataset should be cleaned up quite a bit.

For some reason, there has been some kind of an error in finding the right priors on cell size and empty droplet size.  This is a bit puzzling to me, as CellBender was developed with exactly that kind of dataset in mind.  The debris (as you call it... < 100 UMI counts here) should be ignored by CellBender.  That is the idea behind the `--low-count-threshold` parameter.

Can you try the following command, replacing `input_file.h5` with your filename, and `output.h5` with a filename of your choice?

```
cellbender remove-background --input input_file.h5 --output output.h5 --cuda --expected-cells 9000 --total-droplets-included 20000 --low-count-threshold 100
```

CellBender should be able to give a "prior on counts in empty droplets" very near 200 and a "prior on counts for cells" of between 5k to 15k.  Let me know what you see!  Thanks.

**Comment by vitkl** [comment]
Looks like I get an error again. I am looking at the mouse brain scRNA-seq where cell types have quite different nUMI. Maybe your method is thrown off by the few largest cells and calls the main elbow at 5k UMI as empty droplets. Is the prior supposed to be the mean UMI or some other value (e.g. max)?

You meant to say debris is > 100 UMI, not smaller, right? What I mean by debris are the small fragments of cells and intercellular matrix that contain higher concentration of mRNA than free floating RNA (or soup). And this debris contains specific groups of mRNA compared to fully independent mRNA in soup (I have not examined the data in detail though. Is this how you see this problem too?

```
cellbender:remove-background: 2019-11-18 00:16:48
cellbender:remove-background: Running remove-background
cellbender:remove-background: Loading data from directory ./rawdata/filtered_feature_bc_matrix/folder
cellbender:remove-background: CellRanger v3 format
cellbender:remove-background: Trimming dataset for inference.
cellbender:remove-background: Prior on counts in empty droplets is 5430
cellbender:remove-background: Prior on counts for cells is 46943
cellbender:remove-background: Excluding barcodes with counts below 4344
Traceback (most recent call last):
  File "/home/jovyan/my-conda-envs/cellbender/bin/cellbender", line 11, in <module>
    load_entry_point('cellbender', 'console_scripts', 'cellbender')()
  File "/home/jovyan/CellBender/cellbender/base_cli.py", line 101, in main
    cli_dict[args.tool].run(args)
  File "/home/jovyan/CellBender/cellbender/remove_background/cli.py", line 92, in run
    main(args)
  File "/home/jovyan/CellBender/cellbender/remove_background/cli.py", line 185, in main
    run_remove_background(args)
  File "/home/jovyan/CellBender/cellbender/remove_background/cli.py", line 143, in run_remove_background
    args.low_count_threshold)
  File "/home/jovyan/CellBender/cellbender/remove_background/data/dataset.py", line 90, in __init__
    gene_blacklist=gene_blacklist)
  File "/home/jovyan/CellBender/cellbender/remove_background/data/dataset.py", line 252, in _trim_dataset_for_analysis
    f"There are no empty droplets with UMI counts over the lower " \
AssertionError: There are no empty droplets with UMI counts over the lower cutoff of 4344.  Some empty droplets are necessary for the analysis.  Reduce the --low-count-threshold parameter.
```

**Comment by vitkl** [comment]
Ok, after reading your paper again I think I now get that you suggest that the peak of droplets/barcodes with ~100-500 UMI originates from "Barcode swapping and chimera formation" or "Cross-contamination of capture oligo beads on the microfluidic device" rather than from a biological source. So cell debris and free floating RNA is observed in droplets with less than 100 UMI. Is this a fair summary? 

![image](https://user-images.githubusercontent.com/22567383/69143069-15905300-0ac0-11ea-81f7-058400827f63.png)

**Comment by sjfleming** [comment]
Well, we suggest that the droplets you've highlighted in your plot there are the "empty droplets" whose RNA comes from the various sources we describe, including ambient RNA and barcode swapping / chimera formation.  Droplets with UMI counts below your lines there we believe to be junk from other sources, especially un-corrected barcode sequencing errors.  Everything above the line would probably be real cells.

**Comment by sjfleming** [comment]
But with the correct input parameters, `cellbender remove-background` should definitely be able to identify that the correct prior for empty droplet counts, based on your plot there, is about 200 or so.  The prior is derived from taking a median within a certain range of the dataset.

I've analyzed many many datasets with UMI curves that look just like yours, but I've never run into this behavior.  If the command I suggested above did not work, I would be happy to help debug more.  Is there a way you could share one of the datasets with me?

Have you tried a test analysis using one of the publicly available 10x Gemonics datasets and had `cellbender remove-background` run correctly?

**Comment by sjfleming** [comment]
Something is certainly wrong, since it says that the prior on counts for cells is about 47,000, but I can see from the UMI curve that the highest-count cells have only 10,000 or 20,000 counts at most.

**Comment by bobermayer** [comment]
I just ran into the same error until I realized that I had accidentally passed `filtered_feature_bc_matrix.h5` instead of `raw_feature_bc_matrix.h5` as input file. it looks like the same thing happened here.

**Comment by sjfleming** [comment]
@bobermayer Good to know!  Yes, I have seen this kind of error happen before in the case where the "filtered" file is used by mistake.  I've even done it myself... I should probably try to come up with some heuristic check so that a warning is issued if the file looks like it might be "filtered".

In fact, I will do this, see #99

**Comment by nouhaylaeraysy** [comment]
Hello i run cellbender this is my command : 
cellbender remove-background --input /home/yanis/Bureau/Data2/filtered_feature_bc_matrix_larva1_virilis --output output_file.h5 --expected-cells 15000 --total-droplets-included 100000 --low-count-threshold 50

But i have also the same problems  : 
AssertionError: There are no empty droplets with UMI counts over the lower cutoff of 448.  Some empty droplets are necessary for the analysis.  Reduce the --low-count-threshold parameter.

Do you have an idea how i can solve this?
Thank you in advance.
Best

**Comment by bobermayer** [comment]
see above. you should use the `raw_feature_bc_matrix.h5` as input

**Comment by nouhaylaeraysy** [comment]
Thank you for your response for my data i have used fastq files in order to generate the filtered_feature_bc_matrix do you know how can i found the aw_feature_bc_matrix?

**Comment by sjfleming** [comment]
@nouhaylaeraysy , if you are running [CellRanger](https://support.10xgenomics.com/single-cell-gene-expression/software/pipelines/latest/using/count), for example, you should see an output file called `raw_feature_bc_matrix.h5` when you run the `cellranger count` step and get a folder of output files.

**Comment by nouhaylaeraysy** [comment]
@sjfleming  , yes thank you i used the raw_feature_bc_matrix.h5 but the command still at "Optimal posterior regularization factor"
