### ISSUE TITLE
ERROR reading h5 output in R

### ISSUE THREAD

**Issue by ONeillMB1** [broadinstitute/CellBender#45]
Really excited to see the results of this program! Thanks for the awesome work!

I would like to work in R, ideally within the SimpleSingleCell-verse. I can successfully read the output files with read10xCounts() [DropletUtils], but the count matrix is a "DelayedMatrix" as opposed to the usual "dgCMatrix" and causes downstream errors (not to mention I cannot view the matrix). 

When I follow the code to import into Seurat I get the following error:

> Error in H5File.open(filename, mode, file_create_pl, file_access_pl) : 
>   HDF5-API Errors:
>     error #000: ../../src/hdf5-1.10.0-1/src/H5F.c in H5Fopen(): line 579: unable to open file
>         class: HDF5
>         major: File accessibilty
>         minor: Unable to open file
> 
>     error #001: ../../src/hdf5-1.10.0-1/src/H5Fint.c in H5F_open(): line 1168: unable to lock the file or initialize file structure
>         class: HDF5
>         major: File accessibilty
>         minor: Unable to open file
> 
>     error #002: ../../src/hdf5-1.10.0-1/src/H5FD.c in H5FD_lock(): line 1821: driver lock request failed
>         class: HDF5
>         major: Virtual File Layer
>         minor: Can't update object
> 
>     error #003: ../../src/hdf5-1.10.0-1/src/H5FDsec2.c in H5FD_sec2_lock(): line 939: unable to flock file, errno = 13, error message = 'Permission denied'
>         class: HDF5
>         major: File accessibilty
>         minor: Bad file ID accessed
> 

Any help is appreciated!

**Comment by sjfleming** [comment]
Hi @ONeillMB1, thanks for trying out CellBender!

I have not tried opening the output files using `read10xCounts()` from DropletUtils, but I will check on that.

As for Seurat, that has been tested quite a bit.  Seurat 2 and 3 should all be able to open the CellBender h5 output files using something like

```R
# load Seurat (version 3) library
library(Seurat)

# load data from the filtered h5 file
data.file <- 'tiny_10x_pbmc_filtered.h5'
data.data <- Read10X_h5(filename = data.file, use.names = TRUE)

# create Seurat object
obj <- CreateSeuratObject(counts = data.data)
```

**Comment by ONeillMB1** [comment]
Hi @sjfleming, thank you for the response! 

It appears there was something corrupt about the file I was trying to read in with Seurat - the outputs from all my other libraries seem to work. Apologies!

The "DelayedMatrix" appears to be a new direction that the developers of many Bioconductor single-cell packages are taking (https://osca.bioconductor.org/), whereas the count matrices were previously stored as "dgCMatrix" in the single cell experiment S4 objects. I guess I need to learn how to handle these now...!

Thank you for the interesting work!
