### ISSUE TITLE
FEATURE REQUEST: compatibility with cellranger aggr 

### ISSUE THREAD

**Issue by ONeillMB1** [broadinstitute/CellBender#46]
It would be a nice feature to maintain compatibility with cellRanger aggr. For example, I have run CellBender on several scRNA-seq libraries and would like to use the cellRanger aggr function to downsample libraries to similar sizes.

With version 3 of cellRanger I get the following error:
[error] The molecule info HDF5 file (/pasteur/projets/policy01/evo_immuno_pop/Mary/scRNAseq_MixedLane/cellBender/L1_defaults.h5) was produced by an older version of Cell Ranger. Reading these files is unsupported.

With version 2 of cellRanger I get the following error: 
AttributeError: Illegal column: ambient_expression

**Comment by ONeillMB1** [comment]
Do you have any recommendations on how to subsample the reads from each GEM/library such that all GEM wells/libraries have the same effective sequencing depth from the output of CellBender? This can be achieved with CellRanger aggregate or downsampleReads {DropletUtils}, but neither can read the H5 file produced by CellBender.

**Comment by mbabadi** [comment]
CellRanger's aggr functionality relies on having molecule level information for every batch. The output of `remove-background` is a count matrix and as such, cannot be used as input to aggr. How about running `remove-background` on every batch, obtaining the count matrices, and combining them downstream? if you are worried about sequencing depth heterogeneity across batches, perhaps you could keep track of raw reads per barcode (available in molecule info h5 file) and regress it out from post-`remove-background` count matrix? (e.g. in the same way that scanpy regresses out mito fraction and UMI counts per droplet). The thinking is if sequencing depth variation induces a systematic bias (it actually does), it can be removed to a great extent with linear regression.

**Comment by ONeillMB1** [comment]
Thank you for the suggestions! I ended up downsampling the count matrices before normalizing for library size with downsampleMatrix() of DropletUtils to make comparisons with previous results (scran/scater).
