### ISSUE TITLE
Error writing output files

### ISSUE THREAD

**Issue by clemvigh** [broadinstitute/CellBender#47]
Hi, 

I tried to run CellBender with the following command:
`cellbender remove-background \
                 --input raw_feature_bc_matrix \
                 --output pool_38-2.h5 \
                 --expected-cells 5000 \
                 --total-droplets-included 15000 \
                 --epochs 300`

However, I got the following error in the log file:
`Encountered an error writing output to file pool_38-2.h5.  Output may be incomplete.
Encountered an error writing output to file pool_38-2_filtered.h5.  Output may be incomplete.`

No .h5 output is being produced, only log file, pdf and csv file with cell barcodes, which is not empty.
 
I have attached log file and output pdf here. 
[pool_38-2.log](https://github.com/broadinstitute/CellBender/files/3916066/pool_38-2.log)
[pool_38-2.pdf](https://github.com/broadinstitute/CellBender/files/3916067/pool_38-2.pdf)

Thanks.

**Comment by sjfleming** [comment]
The first thing I notice is that I have never tested using an output filename that has a dash `-` in it... It's possible that the library we use to write h5 files (PyTables) doesn't like that.
Would you be able to try the same command, but with the output file called `pool_38_2.h5`?

**Comment by clemvigh** [comment]
I have now tried that, and I still get the same error message as before.

**Comment by sjfleming** [comment]
Would you be willing to share your data file with me?  That way I can try to debug what's going on.  Feel free to email me at sfleming@broadinstitute.org if you don't want to post the data.

**Comment by sjfleming** [comment]
Also: are you using the Docker image, or your own install of CellBender?  I suspect an issue with h5 writing due to an install issue.  Especially since inference seems to have succeeded, as the other outputs that were created.

**Comment by clemvigh** [comment]
I think it may be because I ran CellBender on a server that only had python 3.6.8, and the example with the tiny pbmc dataset gave the same error as above. I tried to run it locally with python 3.7 and that worked fine.

**Comment by abberclark** [comment]
I am also getting a similar error line: 
`Encountered an error writing output to file cellbender_output/.  Output may be incomplete.`

I used the Docker Image to install CellBender. The h5, csv, log and pdf files were all written to the output directory. Does this mean that CellBender was able to run successfully? 

I have attached the log file here:
[log.txt](https://github.com/broadinstitute/CellBender/files/5778973/log.txt)

Thank you!
Abbe

**Comment by AlexanderAivazidis** [comment]
Hi,

I get exactly the same error. I just installed cellbender according to the instructions here:

https://cellbender.readthedocs.io/en/latest/installation/index.html

and this seemed to work fine.

My python version is 3.7.4 .

I ran cellbender with:

cellbender remove-background \
                 --input raw/ \
                 --output output.h5 \
                 --cuda \
                 --expected-cells 5000 \
                 --total-droplets-included 20000 \
                 --fpr 0.01 \
                 --epochs 150

The log file is attached. Maybe you can suggest a way I should test the PyTables library to ensure it works properly on my system?
Or maybe you have some other ideas how to approach this?

Thanks!
[output.log](https://github.com/broadinstitute/CellBender/files/6604596/output.log)


Alexander
