### ISSUE TITLE
understanding Cellbender output

### ISSUE THREAD

**Issue by deevdevil88** [broadinstitute/CellBender#54]
Hi Stephen,
I was just wondering, is it possible to have a detailed description of what the output.h5 file contains in the various groups? I cannot seem to find it in the readthedocs.

For example there is a group which contamination_fraction(it has 2 sets of values). What to do those mean? is that the lower and upper limit for contamination fraction in the whole dataset?

The ambient expression group, is a list the same length as the number of genes considered in the dataset, however it has only 1 column. So it that the fraction of contamination or ambient expression across all cells per gene?

How can i best evaluate how much ambient RNA or contamination was identified in my sample?

Many thanks
Devika

**Comment by deevdevil88** [comment]
Hello,
I habe identified that in the output.h5 file, the contamination_fraction_param, is actually the Rho values of the model. Do these values need to be between 0-1 or 0%-100% as its a proportion. As when i ran some samples that was in indeed the case. However, in some other samples that i ran recently, this parameter was in the range of 3:126. So how do i interpret these values. many thanks
Devika

**Comment by sjfleming** [comment]
Hi Devika,

Sorry for the delayed response here.

I will work on writing up a more detailed description of each parameter in the readthedocs, that will probably be helpful for everyone.

The ambient expression profile is a list the same length as the number of genes, and it sums to one.  It is the fraction of ambient expression that each gene is responsible for.  It's a normalized gene expression for the ambient background RNA.

The rho values in contamination_fracion_param are the alpha and beta parameters of a beta distribution that controls how much swapping there is globally in the dataset.  So the mean swapping fraction is the mean of that beta distribution, which is alpha / (alpha + beta), or contamination_fracion_param[0] / contamination_fracion_param.sum().  That fractional value will be between 0 and 1.

Hope that makes sense!  Like I said, next update I'll get some more information into the documentation.

Thanks,
Stephen

**Comment by deevdevil88** [comment]
No Worries @sjfleming . I figured the same out by reading the model code. It was very clear. Its glad to know my understanding was correct.
