### ISSUE TITLE
feature_type Key Error

### ISSUE THREAD

**Issue by mtvector** [broadinstitute/CellBender#56]
@sjfleming  Running current v2 branch gives the following error for me:
`Traceback (most recent call last):
  File "/wynton/home/ye/mschmitz1/utils/miniconda3/envs/cellbender/bin/cellbender", line 11, in <module>
    load_entry_point('cellbender', 'console_scripts', 'cellbender')()
  File "/wynton/home/ye/mschmitz1/utils/CellbenderCurrent/CellBender/cellbender/base_cli.py", line 101, in main
    cli_dict[args.tool].run(args)
  File "/wynton/home/ye/mschmitz1/utils/CellbenderCurrent/CellBender/cellbender/remove_background/cli.py", line 102, in run
    main(args)
  File "/wynton/home/ye/mschmitz1/utils/CellbenderCurrent/CellBender/cellbender/remove_background/cli.py", line 195, in main
    run_remove_background(args)
  File "/wynton/home/ye/mschmitz1/utils/CellbenderCurrent/CellBender/cellbender/remove_background/cli.py", line 165, in run_remove_background
  File "/wynton/home/ye/mschmitz1/utils/CellbenderCurrent/CellBender/cellbender/remove_background/data/dataset.py", line 551, in save_to_output_file
    feature_types=self.data['feature_type'],
KeyError: 'feature_type'`

**Comment by sjfleming** [comment]
What is the format of your input data?  Is it CellRanger?  MTX or h5?

**Comment by mtvector** [comment]
MTX. It's not from cellranger but has the same format. I hadn't had issues with it before recent commits.

**Comment by sjfleming** [comment]
Yes, so I have been updating the data parsers to retain gene_name and gene_id info, as well as feature_type info (if it's 10x Genomics v3 chemistry + ).  But I still want it to work in the case that data is not available.  Can you post the result of 
```bash
$ head genes.tsv
```
on your input file?

**Comment by mtvector** [comment]
I've gone with cellranger 3 format, results of `zcat features.tsv.gz | head` are:

`ENSG00000251841.1	RNU6-1334P	Gene Expression
ENSG00000184895.8	SRY	Gene Expression
ENSG00000237659.1	RNASEH2CP1	Gene Expression
ENSG00000232195.1	TOMM22P2	Gene Expression
ENSG00000286130.1	AC006040.1	Gene Expression
ENSG00000129824.16	RPS4Y1	Gene Expression
CATG00000115038.1	CATG00000115038.1	Gene Expression
ENSG00000227289.2	HSFY3P	Gene Expression
ENSG00000229163.2	NAP1L1P2	Gene Expression
CATG00000115039.1	CATG00000115039.1	Gene Expression`

**Comment by mtvector** [comment]
ENSG00000251841.1	RNU6-1334P	Gene Expression
ENSG00000184895.8	SRY	Gene Expression
ENSG00000237659.1	RNASEH2CP1	Gene Expression
ENSG00000232195.1	TOMM22P2	Gene Expression
ENSG00000286130.1	AC006040.1	Gene Expression
ENSG00000129824.16	RPS4Y1	Gene Expression
CATG00000115038.1	CATG00000115038.1	Gene Expression
ENSG00000227289.2	HSFY3P	Gene Expression
ENSG00000229163.2	NAP1L1P2	Gene Expression
CATG00000115039.1	CATG00000115039.1	Gene Expression

**Comment by sjfleming** [comment]
Is it tab `\t` delimited?  Or are those spaces?

**Comment by mtvector** [comment]
They are tabs, just doesn't present well in this format...

**Comment by sjfleming** [comment]
Hmm, okay, I see what happened.  I think you were unlucky enough to pull the branch as I was in the middle of updating things.  There was a typo of 'feature_type' instead of 'feature_types'.  This should be fixed in the branch as it currently stands.  Give that a try.

... the perils of working with a branch under development!  :)  But I am happy to be getting your feedback.
