### ISSUE TITLE
CellBender affecting count matrix data

### ISSUE THREAD

**Issue by piyushjo15** [broadinstitute/CellBender#59]
Hi,

I was comparing the data from CellBender (v2 branch) (CB) and CellRanger (CR) pipeline to understand the quality of cells that are being filtered. I used two single nuclei RNA-seq data.

I performed simple merge analysis to see if I am getting majority of cells in both pipeline and the cells (clusters) which are unique to either approach and how do they look.
However, I observe that CB and CR out don't merge properly. So CB pipeline is affecting raw matric data from CR and introducing some changes in counts ( I didn't specifically check that, but thats how the analysis look)

Cells in approaches after initial filtering:
CB = 8310 (more cells)
CR = 8121

![Slide1](https://user-images.githubusercontent.com/42004111/77167751-e82bd400-6ab6-11ea-9101-7beb4f4280d9.JPG)

In the above UMAP you can see that same cells don't overlap in the merge analysis (I didn't do any batch correction for this).
Also when I look at clusters in them, a lot of them are unique to either and only few overlaps (reverse of my expectations)
![Slide2](https://user-images.githubusercontent.com/42004111/77167757-ed891e80-6ab6-11ea-9a44-a36cae1cc4da.JPG)

Finally I also checked, gene count, UMI count and MT gene proportion (pct.mt). (red: CB; green: CR)
![Slide3](https://user-images.githubusercontent.com/42004111/77167762-f11ca580-6ab6-11ea-98ab-2111bb59a383.JPG)

A lot of the clusters don't have similar feature (because not same cells are assigned to a particular clusters and may be the gene counts are different?)

My question is: is CellBender filtering or affecting gene counts in addition to predicting cell and debris? If it just affecting number of true cells called; then similar cells identified from two approaches (majority of them come from high quality cells) should have similar expression profile and should merge without any batch correction as it is the same sample.

**Comment by mtvector** [comment]
1. Yes it subtracts gene counts likely to be ambient/recombinant
2. Subtracting a bunch of counts will definitely affect cell-cell distances in a way that look like a batch effect. Maybe check out which PCA component CR and CB are separated on if you want more info.
You may want to check out the manuscript on biorxiv if you have these questions, they're pretty fundamental! Then again I'm just a person who follows this repo

**Comment by piyushjo15** [comment]
Thanks for the information mtvector. I gleamed over the manuscript and didn't pay attention to the details. Thanks for pointing it out to me.
