### ISSUE TITLE
Differential gene analysis after CellBender

### ISSUE THREAD

**Issue by TheSingleCell** [broadinstitute/CellBender#61]
Dear team,
Thank you very much for developing CellBender! I have a question regarding the downstream analysis after CellBender. My scRNA-seq design includes three control samples plus three disease samples. My goal in this study was to identify the cell type specific disease markers. My question is: If I run CellBender on each dataset separately, can I perform differential gene analysis directly on the gene expression values generated by CellBender to compare the disease versus control?
Your comments will be greatly appreciated!
Best,
Nelson

**Comment by mbabadi** [comment]
Hi @TheSingleCell,

Thank you for using CellBender!

You can proceed with any reasonable DE analysis method after you run CellBender remove-background on each dataset separately -- think of the output of CellBender remove-background as a plug-in for the count matrix you currently feed to your workflows. CellBender remove-background sanitizes the count matrix from background RNA while removing genuinely empty droplets (i.e. droplets that are statistically likely to be empty). It is likely that you will still get a large number of low quality droplets e.g. droplets containing dead cells, debris, etc, as well as doublets. It is advised that you further cleanup post-CellBender count matrices by performing your own QC before DE analysis.
