### ISSUE TITLE
QUESTION: Future of CelllBender?

### ISSUE THREAD

**Issue by mtvector** [broadinstitute/CellBender#65]
Hi there,
Love the model and the interface of cellbender! Works great as a step two in my kallisto pipeline! I've been using V2 for a while and I'm hoping to publish a scRNAseq study in the near future, though there are still issues with NaNs during training or no cells detected on a few samples that I've been working around. I'm wondering how much you expect to change in v2 or V2.1+ in the near future, approximately when that might be, and maybe what a roadmap for the future of the project is!
Thanks so much for making such a nice tool for the community!
Matthew

**Comment by sjfleming** [comment]
Hi Matthew,

Glad to hear you've been getting into using v2 already.  Several groups at the Broad are also using it currently in their scRNA-seq work.  Here's the plan: what is currently the v2.1 branch will be further tweaked a little bit in some of the implementation details.  Some things will change a little, but the changes to the inputs and outputs should be relatively minor.  We expect the performance to be basically the same, and we are really looking for improvements in auto-setting of input parameters and improvements on difficult datasets which are kind of edge-cases.

The plan is to have an official release (which will probably eventually be called 0.2) within the next month or two.  This release will be accompanied by a paper.  We plan to put that paper up on bioRxiv at the same time that we'll be submitting it to a journal for publication.

Thanks for using the tool!
And please keep letting us know any feedback you might have.  (Still working on making sure those NaN and no cells issues go away.)

Stephen
