### ISSUE TITLE
Cannot import cycler 

### ISSUE THREAD

**Issue by aralbright** [broadinstitute/CellBender#74]
Hi, 

I'm trying to run a cellbender job for the first time on a server and I'm getting the following error:

```   
from cycler import Cycler, cycler as ccycler
ImportError: cannot import name 'Cycler' from 'cycler' (/global/home/users/aralbright/.local/lib/python3.7/site-packages/cycler.py)

```

I ran cellbender -h like in the other github issue with a similar error and I do get the same thing. I'm using a conda environment on the server and I followed the manual installation instruction in the docs. I'm not sure how to figure out the issue if someone could help me out. 

Thanks! 

Ashley

**Comment by sjfleming** [comment]
Hi Ashley,

I _think_ `cycler` is getting imported as part of `matplotlib`.  `cellbender` does not ever directly import `cycler`, so I am thinking that the `ImportError` you're showing is probably occurring within `matplotlib` itself.  Is there a way for you to check and see if your installation of `matplotlib` is up-to-date and functional?  Maybe if you start a python kernel and then try typing
```python
import matplotlib
import matplotlib.pyplot as plt
```
If you don't get an error there, then we'll have to keep thinking...

**Comment by aralbright** [comment]
You were definitely right, I couldn't import matplotlib properly for whatever reason and was getting the same error. I tried reinstalling matplotlib and that didn't help matters, so I'll keep digging into it. Thanks!
