### ISSUE TITLE
error when install CellBender

### ISSUE THREAD

**Issue by honghh2018** [broadinstitute/CellBender#82]
Hi @all,
     Thanks for develop the great tools  for ambient RNA deleted.
      The error occurred when the installed step had go finished.
       The error showing below
![image](https://user-images.githubusercontent.com/41668708/98803645-0bddc900-2450-11eb-9a54-f8213e7cf5e9.png)
       I use the *.tar.gz file to tar zxf and then come in and type the python setup.py install. so when it over,
       I run the cellbender --version showing the error post above.
       Best,
       hanhuihong

**Comment by sjfleming** [comment]
I wonder if you are missing part of the code, specifically the folder called `remove-background`?
Can you try to install by moving into the directory that contains `setup.py` and typing

```command
pip install -e .
```

Then try
```command
cellbender -h
```
and
```command
cellbender remove-background -h
```

**Comment by honghh2018** [comment]
Excellent! It work well, Thanks again.
