### ISSUE TITLE
PR for AnnData support?

### ISSUE THREAD

**Issue by jacobkimmel** [broadinstitute/CellBender#88]
Hi CellBender team,

Would you all be interested in adding support for `anndata` objects as inputs?
These are the default output of `kallisto | bustools` based pseudoalignment tools.

I added an implementation through `.data.dataset` that I can PR if you're open to it.
No worries if you'd rather not include this in the full release -- I can keep it in my fork :).

Thanks!
Jacob

**Comment by sjfleming** [comment]
Hi Jacob,

Thanks for your interest, and yes, we would be interested in that kind of a contribution.  If you could make a PR, we will take a look!

Thanks,
Stephen

**Comment by mbabadi** [comment]
Hi Jacob,

Thanks for using CellBender -- we hope that you've found it useful in your work!

Regarding `anndata` support:  it'd be a great contribution and we'd appreciate it. We had it in our purview to add support for additional tools and file formats, including `kallisto | bustools` and `salmon alevin` -- we can set this in motion with your PR!

I'd just like note that adding support for `anndata` is a bit tricky as it is "too flexible":  it could have come from many sources, including the raw output from kallisto (good), or an interactive scanpy session (probably bad). It will be very necessary to thoroughly assert that than provided file is legitimate (e.g. raw and unprocessed, includes the necessary metadata, includes all barcodes and not just the cells, etc) and not hesitating to fail fast.

Finally, we do not have an official code style guideline yet; we tend to stick to `PEP08` rather strictly though.

We look forward to your PR and starting a conversation!

Best,
Mehrtash

**Comment by mbabadi** [comment]
@sjfleming ah, you beat me to it haha! ;-)

**Comment by mbabadi** [comment]
thanks you @jacobkimmel for your contribution! :-) closing the issue.
