### ISSUE TITLE
"No cells found! Cannot compute expected FPR." Error

### ISSUE THREAD

**Issue by vincentnmiao** [broadinstitute/CellBender#94]
Hi, thanks for developing CellBender, we've found it works great for a lot of our recent applications in the lab! I'm running into some trouble post-inference when writing out outputs - a "No cells found! Cannot compute expected FPR." error. The dataset I'm working on is very noisy (some issues arose in the wet lab with these samples), and I've tried varying some of the parameters (expected_cells, fpr), without success. The output log is attached. Do you have any suggestions for what I can try, or is the dataset in a regime where CellBender is unable to recover the ambient fraction? Thanks!
[6202b64d-ddfd-49f3-8a93-0b3b78bc9cf7_cellbender_remove_background_af081b43-fa51-4d19-9b47-25e9c2ce38c9_call-run_cellbender_remove_background_gpu_run_cellbender_remove_background_gpu.txt](https://github.com/broadinstitute/CellBender/files/6218709/6202b64d-ddfd-49f3-8a93-0b3b78bc9cf7_cellbender_remove_background_af081b43-fa51-4d19-9b47-25e9c2ce38c9_call-run_cellbender_remove_background_gpu_run_cellbender_remove_background_gpu.txt)

**Comment by sjfleming** [comment]
Thanks for trying it out!  Hopefully we can get this resolved...

I see that the files appears to have loaded correctly... I'm seeing 
```
CellRanger v3 format
cellbender:remove-background: Trimming dataset for inference.
cellbender:remove-background: Including 25518 genes that have nonzero counts.
cellbender:remove-background: Prior on counts in empty droplets is 220
cellbender:remove-background: Prior on counts for cells is 1324
cellbender:remove-background: Excluding barcodes with counts below 110
```
which all looks good.  Does a cell count of around 1300 UMIs sound about right for this dataset?  And an empty droplet plateau level of about 200 UMIs per empty droplet?
Without having seen your particular dataset, it does seem like these values are within the realm of possibility.

The next line though might indicate an issue:
```
Using 500 probable cell barcodes, plus an additional 9582 barcodes, and 0 empty droplets.
```

So, typically I see non-zero numbers of "empty droplets" being included from a dataset.  I wonder if there are only 9582+500 droplets in this dataset?  Has the dataset been trimmed at all?  Or are all the barcodes from CellRanger's "raw" output file included?

If this is the totally "raw" file with all the droplets included, then I may have a couple more questions...

**Comment by vincentnmiao** [comment]
Thanks for helping with this! The UMI/cell and UMI/empty sound reasonable - these are relatively unhealthy PBMCs to start with. These data are from Seq-Well (drop-seq chemistry) aligned using STAR and forced to output 20000 barcodes (we expect ~1000 cells, so 95% barcodes representing ambient) and untrimmed. We've used this strategy in the past with other datasets generated with Seq-Well, and it's worked great (even with forcing just 10000 barcodes for ~1000 cells).  

I just re-checked the h5 file to make sure the dimensions are what we expect them to be, and I don't think there's a problem with aligning/pre-processing the file since 21/24 samples for this project were cellbender'd successfully using the same pipeline.

**Comment by vincentnmiao** [comment]
Wanted to follow up here if you have any suggestions, thanks!

**Comment by sjfleming** [comment]
Hi!  Sorry for the delay.  I see... you're using a SeqWell pipeline that outputs 20k barcodes.

I would be interested in taking a look at what's going on in your case.  I have not had a chance to try out that kind of dataset yet, and it's possible that I might need to play around a little bit to see why no cells were found here.  Do you have the ability to share a test file with me somehow?

**Comment by sjfleming** [comment]
(Resolved via email as a potentially all-ambient dataset, without enough cells for CellBender to work.)

**Comment by satheshsiva** [comment]
Hi I have the same issue now. Can you please help me to resolve the issue. My data is slightly higher contamination level compared with normal one. I tried to increase the FPR value. But it failed again. Please let me know any suggestions. Thanks.
