### ISSUE TITLE
Command line argument to limit posterior generation memory usage

### ISSUE THREAD

**Issue by sjfleming** [broadinstitute/CellBender#98]
Create a new input argument to control the batch size used by the posterior inference step.

Unclear if the problematic line is here
https://github.com/broadinstitute/CellBender/blob/0feb5e0f8867332d3c55711e4390dd4f5b03fa18/cellbender/remove_background/infer.py#L413

or here
https://github.com/broadinstitute/CellBender/blob/0feb5e0f8867332d3c55711e4390dd4f5b03fa18/cellbender/remove_background/infer.py#L383

but figure this out.

Also explore memory usage during posterior generation.  Why is it spiking?  Is this avoidable?

**Comment by sjfleming** [comment]
Totally clearing out CUDA memory after training but before posterior generation seems to help out a lot.  Not sure if it will totally solve this for everybody, but this will be in the 0.3.0 release, and should fix the issue for most people

**Comment by hoondy** [comment]
Changing `batch_size=20,` and `n_cells = min(10, cell_inds.size)` from `CellBender/cellbender/remove_background/infer.py` worked for me.

**Comment by sjfleming** [comment]
Closed by #238
